steps:
  # Build de la API (.NET backend)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --target
      - api-runtime
      - -t
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/api:latest
      - .

  # Build del Client (Blazor WASM + nginx)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --target
      - client-runtime
      - -t
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/client:latest
      - .

  # Push de las imágenes a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/api:latest

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/client:latest

  # Deploy automático a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - figuritacs-api
      - --image
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/api:latest
      - --region
      - southamerica-east1

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - figuritacs-client
      - --image
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/client:latest
      - --region
      - southamerica-east1

options:
  logging: CLOUD_LOGGING_ONLY
