steps:
  # Build de la API (.NET 10 backend)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --target
      - api-runtime
      - -t
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/api:latest
      - .

  # Build del Client (Blazor WASM + nginx)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --target
      - client-runtime
      - -t
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/client:latest
      - .

images:
  - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/api:latest
  - southamerica-east1-docker.pkg.dev/$PROJECT_ID/figuritacs/client:latest

options:
  logging: CLOUD_LOGGING_ONLY
